# Site settings
title: Blog 42
email: peter.grman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about solutions to challenges, I encounter during my studies & work.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://peter.grman.at" # the base hostname & protocol for your site
twitter_username: grmanp
github_username:  pgrm
permalink: "/:title/"
google_analytics_id: UA-40793217-1
disqus_shortname: blog42

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jemoji

jekyll-mentions:
  base_url: https://twitter.com

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
    values:
      author: "Peter"
      greeting: "Happy Coding!"
